name: CI

on:
  pull_request:
    branches:
      - 'dev'

jobs:
  install-test-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node: [14]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
      - run: npm run build
